### ISSUE TITLE
Modelagem

### ISSUE THREAD

**Issue by bmarchete** [igorteruel/estoque#1]
A tabela estoque não me permite cadastrar novos produto, apenas controlar o estoque de um produto que não existe? Como isso é possível? 😞

**Comment by liandrinha12** [comment]
Estamos trabalhando para solucionar o problema :cry:

**Comment by bmarchete** [comment]
Igor, se continuar nessa pegada seu grupo vai ficar sem nota. Vocês não fizeram as cinco perguntas ainda e essa modelagem me parece um pouco confusa! @igorteruel
