### ISSUE TITLE
Tabelas

### ISSUE THREAD

**Issue by MarrentaxD** [igorteruel/estoque#2]
Infelizmente o seu Banco deveria conter as tabelas prontas e as perguntas formuladas corretamente!
:disappointed: :rage:

**Comment by MarrentaxD** [comment]
Gostaria de ser respondida :squirrel:

**Comment by liandrinha12** [comment]
Ja vamos resolver o problema :sob:

**Comment by MarrentaxD** [comment]
ok :wink:

**Comment by MarrentaxD** [comment]
Fico no Aguardo!! :alarm_clock:  :confused:

**Comment by igorteruel** [comment]
problema resolvido...
caso algo me passou batido, notifique.

**Comment by igorteruel** [comment]
responda as primeiras questões.
 as demais logo serão inseridas

**Comment by igorteruel** [comment]
eu não escrevi desse modo :boom: :angry: :rage:

**Comment by Nawanzera** [comment]
Está ocorrendo erros na criação da tabela, ao chegar no produto 37 ( papel mache) está ocorrendo um erro :boom:
