### ISSUE TITLE
Dica

### ISSUE THREAD

**Issue by MarrentaxD** [igorteruel/estoque#3]
Arrumar os Arquivos corretamente!, exemplo README; :paperclip:

**Comment by igorteruel** [comment]
o readme foi atualizado para perguntas :+1:

**Comment by bmarchete** [comment]
@igorteruel Conforme apresentado em aula, o arquivo deve se chamar Readme.md, pois esse é o padrão que o Github usa para apresentar o texto no inicio. Favor arrumar!
